const colors = {
  light: {
    text: "#1C1C1E",
    tint: "#FF3B30",
    background: "#F2F2F7",
    foreground: "#1C1C1E",
    card: "#FFFFFF",
    cardForeground: "#1C1C1E",
    primary: "#FF3B30",
    primaryForeground: "#FFFFFF",
    secondary: "#E9E9EB",
    secondaryForeground: "#1C1C1E",
    muted: "#E9E9EB",
    mutedForeground: "#8E8E93",
    accent: "#FF9500",
    accentForeground: "#FFFFFF",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#C6C6C8",
    input: "#E9E9EB",
    success: "#34C759",
    successForeground: "#FFFFFF",
    warning: "#FF9500",
    warningForeground: "#FFFFFF",
    info: "#007AFF",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#FF453A",
    background: "#000000",
    foreground: "#FFFFFF",
    card: "#1C1C1E",
    cardForeground: "#FFFFFF",
    primary: "#FF453A",
    primaryForeground: "#FFFFFF",
    secondary: "#2C2C2E",
    secondaryForeground: "#FFFFFF",
    muted: "#2C2C2E",
    mutedForeground: "#8E8E93",
    accent: "#FF9F0A",
    accentForeground: "#FFFFFF",
    destructive: "#FF453A",
    destructiveForeground: "#FFFFFF",
    border: "#38383A",
    input: "#2C2C2E",
    success: "#30D158",
    successForeground: "#FFFFFF",
    warning: "#FF9F0A",
    warningForeground: "#FFFFFF",
    info: "#0A84FF",
  },
  radius: 12,
};

export default colors;
